// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/admin" | "/admin/connectors" | "/admin/licences" | "/admin/metrics" | "/admin/orgs" | "/admin/orgs/[id]" | "/audit" | "/backup" | "/billing" | "/cash-bank" | "/companies" | "/connect" | "/customise" | "/developer" | "/devices" | "/document" | "/entry" | "/gst" | "/help" | "/help/[id]" | "/insights" | "/invoice/[id]" | "/items" | "/items/[name]" | "/kpi" | "/login" | "/notifications" | "/numbering" | "/onboarding" | "/outstanding" | "/parties" | "/parties/[name]" | "/partner" | "/pulse" | "/reminders" | "/reports" | "/security" | "/settings" | "/sync" | "/txn/[section]" | "/txn/[section]/[id]" | "/users"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/admin": {}
  "/admin/connectors": {}
  "/admin/licences": {}
  "/admin/metrics": {}
  "/admin/orgs": {}
  "/admin/orgs/[id]": { "id": string; }
  "/audit": {}
  "/backup": {}
  "/billing": {}
  "/cash-bank": {}
  "/companies": {}
  "/connect": {}
  "/customise": {}
  "/developer": {}
  "/devices": {}
  "/document": {}
  "/entry": {}
  "/gst": {}
  "/help": {}
  "/help/[id]": { "id": string; }
  "/insights": {}
  "/invoice/[id]": { "id": string; }
  "/items": {}
  "/items/[name]": { "name": string; }
  "/kpi": {}
  "/login": {}
  "/notifications": {}
  "/numbering": {}
  "/onboarding": {}
  "/outstanding": {}
  "/parties": {}
  "/parties/[name]": { "name": string; }
  "/partner": {}
  "/pulse": {}
  "/reminders": {}
  "/reports": {}
  "/security": {}
  "/settings": {}
  "/sync": {}
  "/txn/[section]": { "section": string; }
  "/txn/[section]/[id]": { "section": string; "id": string; }
  "/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
