-- The public API: keys, webhooks and a log.
--
-- Separate from the app's own session tokens on purpose. A session belongs to a
-- person and dies when they sign out; an API key belongs to a piece of software
-- and has to outlive everybody, so mixing the two means either sessions that
-- never expire or integrations that break when somebody leaves.

CREATE TABLE IF NOT EXISTS api_keys (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id       uuid NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  name         text NOT NULL,
  -- Only the hash. The key itself is shown once, at creation, and is then
  -- unrecoverable - the same reason a password is not stored.
  key_hash     text NOT NULL UNIQUE,
  -- The first characters, kept in clear so somebody can tell two keys apart in
  -- a list without being able to use either.
  prefix       text NOT NULL,
  -- Which of the twelve modules this key may read, as an array rather than the
  -- full permission grid: an integration reads, and a key that can do anything
  -- a human role can do is a key that can delete a business.
  scopes       text[] NOT NULL DEFAULT '{}',
  -- Optional narrowing to one set of books.
  company_id   uuid REFERENCES companies(id) ON DELETE CASCADE,
  created_by   uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  last_ip      text NOT NULL DEFAULT '',
  expires_at   timestamptz,
  revoked_at   timestamptz,
  calls        bigint NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS api_keys_org_idx ON api_keys (org_id) WHERE revoked_at IS NULL;

-- Webhooks: Munim telling somebody else's software that something happened.
CREATE TABLE IF NOT EXISTS webhooks (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id       uuid NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  url          text NOT NULL,
  events       text[] NOT NULL DEFAULT '{}',
  -- Every delivery is signed with this so the receiver can tell a real one from
  -- anybody who guessed the URL. Generated by Munim, shown once.
  secret       text NOT NULL,
  active       boolean NOT NULL DEFAULT true,
  created_by   uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  -- A endpoint that has been failing for days should stop being retried, and
  -- somebody should be told why rather than finding out from silence.
  last_status  int,
  last_error   text NOT NULL DEFAULT '',
  last_at      timestamptz,
  failures     int NOT NULL DEFAULT 0,
  disabled_at  timestamptz
);

CREATE INDEX IF NOT EXISTS webhooks_org_idx ON webhooks (org_id) WHERE active;

-- One attempted delivery.
CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  webhook_id   uuid NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,
  org_id       uuid NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  event        text NOT NULL,
  payload      jsonb NOT NULL DEFAULT '{}'::jsonb,
  status       int,
  error        text NOT NULL DEFAULT '',
  attempt      int NOT NULL DEFAULT 1,
  duration_ms  int,
  at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS webhook_deliveries_idx
  ON webhook_deliveries (webhook_id, at DESC);

-- What the API was asked for.
--
-- Kept because "your integration stopped working" is otherwise unanswerable,
-- and because an API key that starts being used from a new country is worth
-- being able to see.
CREATE TABLE IF NOT EXISTS api_log (
  id          bigserial PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  api_key_id  uuid REFERENCES api_keys(id) ON DELETE SET NULL,
  method      text NOT NULL,
  path        text NOT NULL,
  status      int NOT NULL,
  duration_ms int NOT NULL DEFAULT 0,
  ip_prefix   text NOT NULL DEFAULT '',
  error       text NOT NULL DEFAULT '',
  at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS api_log_org_idx ON api_log (org_id, at DESC);
CREATE INDEX IF NOT EXISTS api_log_key_idx ON api_log (api_key_id, at DESC);
